<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeoRepository extends EntityRepository
{
    public function getHazardous()
    {
        return $this->findBy(['isHazardous' => true]);
    }


    public function getFastestByHazardous(bool $hazardous)
    {
        return $this->findOneBy(
            ['isHazardous' => $hazardous],
            ['speed' => 'DESC'],
            ['limit' => 1]
        );
    }
}
